packages: []

allowBuilds:
  esbuild: true
  sharp: true
  msw: false

minimumReleaseAgeExclude:
  - "@contentbit/astro@0.3.0"
  - "@contentbit/blocks@0.3.0"
  - "@contentbit/core@0.3.0"
  - "@contentbit/html@0.3.0"
  - contentbit@0.3.0
